@url = http://localhost:3044

### TEST
GET {{url}}

### LOGIN
POST {{url}}/login
content-type: application/json

{
    "username": "jason",
    "password": "jason123"
}

### MAINTAIN LOGIN
POST {{url}}/maintain-login
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImhhbnMiLCJmaXJzdE5hbWUiOiJIYW5zIiwibGFzdE5hbWUiOiJSaWNodGVyIn0sImlhdCI6MTY1NzcxNDE5MiwiZXhwIjoxNjU3NzE0MjEyfQ.E02hT17cB5s74E7xU54LBqk6n7TD-K9zbNg4l_vmv_o